<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('cities')->insert(['name' => 'Alaminos', 'description' => 'Pangasinan, Region I']);
        DB::table('cities')->insert(['name' => 'Angeles', 'description' => 'Pampanga, Region III']);
        DB::table('cities')->insert(['name' => 'Antipolo', 'description' => 'Rizal, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Bacolod', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Bacoor', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Bago', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Baguio', 'description' => 'Benguet, CAR']);
        DB::table('cities')->insert(['name' => 'Bais', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'Balanga', 'description' => 'Bataan, Region III']);
        DB::table('cities')->insert(['name' => 'Batac', 'description' => 'Ilocos Norte, Region I']);
        DB::table('cities')->insert(['name' => 'Batangas', 'description' => 'Batangas, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Bayawan', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'Baybay', 'description' => 'Leyte, Region VIII']);
        DB::table('cities')->insert(['name' => 'Bayugan', 'description' => 'Agusan del Sur, Region XIII']);
        DB::table('cities')->insert(['name' => 'Biñan', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Bislig', 'description' => 'Surigao del Sur, Region XIII']);
        DB::table('cities')->insert(['name' => 'Bogo', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Borongan', 'description' => 'Eastern Samar, Region VIII']);
        DB::table('cities')->insert(['name' => 'Butuan', 'description' => 'Agusan del Norte, Region XIII']);
        DB::table('cities')->insert(['name' => 'Cabadbaran', 'description' => 'Agusan del Norte, Region XIII']);
        DB::table('cities')->insert(['name' => 'Cabanatuan', 'description' => 'Nueva Ecija, Region III']);
        DB::table('cities')->insert(['name' => 'Cabuyao', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Cadiz', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Cagayan de Oro', 'description' => 'Misamis Oriental, Region X']);
        DB::table('cities')->insert(['name' => 'Calamba', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Calapan', 'description' => 'Oriental Mindoro, Region IV-B']);
        DB::table('cities')->insert(['name' => 'Calbayog', 'description' => 'Samar (Western), Region VIII']);
        DB::table('cities')->insert(['name' => 'Caloocan', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Candon', 'description' => 'Ilocos Sur, Region I']);
        DB::table('cities')->insert(['name' => 'Canlaon', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'Carcar', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Catbalogan', 'description' => 'Samar (Western), Region VIII']);
        DB::table('cities')->insert(['name' => 'Cauayan', 'description' => 'Isabela, Region II']);
        DB::table('cities')->insert(['name' => 'Cavite', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Cebu', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Cotabato', 'description' => 'Maguindanao, Region XII']);
        DB::table('cities')->insert(['name' => 'Dagupan', 'description' => 'Pangasinan, Region I']);
        DB::table('cities')->insert(['name' => 'Danao', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Dapitan', 'description' => 'Zamboanga del Norte, Region IX']);
        DB::table('cities')->insert(['name' => 'Dasmariñas', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Davao', 'description' => 'Davao del Sur, Region XI']);
        DB::table('cities')->insert(['name' => 'Digos', 'description' => 'Davao del Sur, Region XI']);
        DB::table('cities')->insert(['name' => 'Dipolog', 'description' => 'Zamboanga del Norte, Region IX']);
        DB::table('cities')->insert(['name' => 'Dumaguete', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'El Salvador', 'description' => 'Misamis Oriental, Region X']);
        DB::table('cities')->insert(['name' => 'Escalante', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Gapan', 'description' => 'Nueva Ecija, Region III']);
        DB::table('cities')->insert(['name' => 'General Santos', 'description' => 'South Cotabato, Region XII']);
        DB::table('cities')->insert(['name' => 'Gingoog', 'description' => 'Misamis Oriental, Region X']);
        DB::table('cities')->insert(['name' => 'Guihulngan', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'Himamaylan', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Ilagan', 'description' => 'Isabela, Region II']);
        DB::table('cities')->insert(['name' => 'Iligan', 'description' => 'Lanao del Norte, Region X']);
        DB::table('cities')->insert(['name' => 'Iloilo', 'description' => 'Iloilo, Region VI']);
        DB::table('cities')->insert(['name' => 'Imus', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Iriga', 'description' => 'Camarines Sur, Region V']);
        DB::table('cities')->insert(['name' => 'Isabela', 'description' => 'Basilan, Region IX']);
        DB::table('cities')->insert(['name' => 'Kabankalan', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Kidapawan', 'description' => 'Cotabato (North), Region XII']);
        DB::table('cities')->insert(['name' => 'Koronadal', 'description' => 'South Cotabato, Region XII']);
        DB::table('cities')->insert(['name' => 'La Carlota', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Lamitan', 'description' => 'Basilan, ARMM']);
        DB::table('cities')->insert(['name' => 'Laoag', 'description' => 'Ilocos Norte, Region I']);
        DB::table('cities')->insert(['name' => 'Lapu-Lapu', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Las Piñas', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Legazpi', 'description' => 'Albay, Region V']);
        DB::table('cities')->insert(['name' => 'Ligao', 'description' => 'Albay, Region V']);
        DB::table('cities')->insert(['name' => 'Lipa', 'description' => 'Batangas, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Lucena', 'description' => 'Quezon, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Maasin', 'description' => 'Southern Leyte, Region VIII']);
        DB::table('cities')->insert(['name' => 'Mabalacat', 'description' => 'Pampanga, Region III']);
        DB::table('cities')->insert(['name' => 'Makati', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Malabon', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Malaybalay', 'description' => 'Bukidnon, Region X']);
        DB::table('cities')->insert(['name' => 'Malolos', 'description' => 'Bulacan, Region III']);
        DB::table('cities')->insert(['name' => 'Mandaluyong', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Mandaue', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Manila', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Marawi', 'description' => 'Lanao del Sur, ARMM']);
        DB::table('cities')->insert(['name' => 'Marikina', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Masbate', 'description' => 'Masbate, Region V']);
        DB::table('cities')->insert(['name' => 'Mati', 'description' => 'Davao Oriental, Region XI']);
        DB::table('cities')->insert(['name' => 'Meycauayan', 'description' => 'Bulacan, Region III']);
        DB::table('cities')->insert(['name' => 'Muñoz', 'description' => 'Nueva Ecija, Region III']);
        DB::table('cities')->insert(['name' => 'Muntinlupa', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Naga', 'description' => 'Camarines Sur, Region V']);
        DB::table('cities')->insert(['name' => 'Naga', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Navotas', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Olongapo', 'description' => 'Zambales, Region III']);
        DB::table('cities')->insert(['name' => 'Ormoc', 'description' => 'Leyte, Region VIII']);
        DB::table('cities')->insert(['name' => 'Oroquieta', 'description' => 'Misamis Occidental, Region X']);
        DB::table('cities')->insert(['name' => 'Ozamiz', 'description' => 'Misamis Occidental, Region X']);
        DB::table('cities')->insert(['name' => 'Pagadian', 'description' => 'Zamboanga del Sur, Region IX']);
        DB::table('cities')->insert(['name' => 'Palayan', 'description' => 'Nueva Ecija, Region III']);
        DB::table('cities')->insert(['name' => 'Panabo', 'description' => 'Davao del Norte, Region XI']);
        DB::table('cities')->insert(['name' => 'Parañaque', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Pasay', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Pasig', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Passi', 'description' => 'Iloilo, Region VI']);
        DB::table('cities')->insert(['name' => 'Puerto Princesa', 'description' => 'Palawan, Region IV-B']);
        DB::table('cities')->insert(['name' => 'Quezon', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Roxas', 'description' => 'Capiz, Region VI']);
        DB::table('cities')->insert(['name' => 'Sagay', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Samal', 'description' => 'Davao del Norte, Region XI']);
        DB::table('cities')->insert(['name' => 'San Carlos', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'San Carlos', 'description' => 'Pangasinan, Region I']);
        DB::table('cities')->insert(['name' => 'San Fernando', 'description' => 'La Union, Region I']);
        DB::table('cities')->insert(['name' => 'San Fernando', 'description' => 'Pampanga, Region III']);
        DB::table('cities')->insert(['name' => 'San Jose', 'description' => 'Nueva Ecija, Region III']);
        DB::table('cities')->insert(['name' => 'San Jose del Monte', 'description' => 'Bulacan, Region III']);
        DB::table('cities')->insert(['name' => 'San Juan', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'San Pablo', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'San Pedro', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Santa Rosa', 'description' => 'Laguna, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Santiago', 'description' => 'Isabela, Region II']);
        DB::table('cities')->insert(['name' => 'Silay', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Sipalay', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Sorsogon', 'description' => 'Sorsogon, Region V']);
        DB::table('cities')->insert(['name' => 'Surigao', 'description' => 'Surigao del Norte, Region XIII']);
        DB::table('cities')->insert(['name' => 'Tabaco', 'description' => 'Albay, Region V']);
        DB::table('cities')->insert(['name' => 'Tabuk', 'description' => 'Kalinga, CAR']);
        DB::table('cities')->insert(['name' => 'Tacloban', 'description' => 'Leyte, Region VIII']);
        DB::table('cities')->insert(['name' => 'Tacurong', 'description' => 'Sultan Kudarat, Region XII']);
        DB::table('cities')->insert(['name' => 'Tagaytay', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Tagbilaran', 'description' => 'Bohol, Region VII']);
        DB::table('cities')->insert(['name' => 'Taguig', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Tagum', 'description' => 'Davao del Norte, Region XI']);
        DB::table('cities')->insert(['name' => 'Talisay', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Talisay', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Tanauan', 'description' => 'Batangas, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Tandag', 'description' => 'Surigao del Sur, Region XIII']);
        DB::table('cities')->insert(['name' => 'Tangub', 'description' => 'Misamis Occidental, Region X']);
        DB::table('cities')->insert(['name' => 'Tanjay', 'description' => 'Negros Oriental, NIR']);
        DB::table('cities')->insert(['name' => 'Tarlac', 'description' => 'Tarlac, Region III']);
        DB::table('cities')->insert(['name' => 'Tayabas', 'description' => 'Quezon, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Toledo', 'description' => 'Cebu, Region VII']);
        DB::table('cities')->insert(['name' => 'Trece Martires', 'description' => 'Cavite, Region IV-A']);
        DB::table('cities')->insert(['name' => 'Tuguegarao', 'description' => 'Cagayan, Region II']);
        DB::table('cities')->insert(['name' => 'Urdaneta', 'description' => 'Pangasinan, Region I']);
        DB::table('cities')->insert(['name' => 'Valencia', 'description' => 'Bukidnon, Region X']);
        DB::table('cities')->insert(['name' => 'Valenzuela', 'description' => 'NCR']);
        DB::table('cities')->insert(['name' => 'Victorias', 'description' => 'Negros Occidental, NIR']);
        DB::table('cities')->insert(['name' => 'Vigan', 'description' => 'Ilocos Sur, Region I']);
        DB::table('cities')->insert(['name' => 'Zamboanga', 'description' => 'Zamboanga del Sur, Region IX']);
    }
}
